### ISSUE TITLE
a simple error?

### ISSUE THREAD

**Issue by flyingtiger111** [kdhRick2222/SANFlow#1]
The default value of c.dec_arch in config.py is sanflow.
 the same two pieces of code appear in model.py's“ load_decoder_arch”

`def load_decoder_arch(c, dim_in):
    if c.dec_arch == 'freia-flow':
        decoder = freia_flow_head(c, dim_in)
    elif c.dec_arch == 'freia-cflow':
        decoder = freia_cflow_head(c, dim_in)
    else:
        raise NotImplementedError('{} is not supported NF!'.format(c.dec_arch))
    return decoder`

Can you tell me where sanflow is?
without sanflow, there is a error“NotImplementedError: sanflow is not supported NF!”

**Comment by kdhRick2222** [comment]
Thank you and sorry for notification. It will run. I just fixed it.
