### ISSUE TITLE
a small request

### ISSUE THREAD

**Issue by xiaoyuan4513** [kdhRick2222/SANFlow#2]
I see that you have provided some code to generate synthetic anomaly images, such as **make_circlemask.py** could generate circular shaped patches.
Could you provide code to make rectangular shaped patches?
Thank you very much!

**Comment by xiaoyuan4513** [comment]
dear scholar, please

**Comment by kdhRick2222** [comment]
I'm so sorry for replying late. I just uploaded it. Have a nice day.
